- name: Manage Grafana
  hosts: webservers
  become: true
  tasks:
    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory

    - name: Download Grafana tarball
      get_url:
        url: https://dl.grafana.com/oss/release/grafana-11.1.3.linux-amd64.tar.gz
        dest: /home/ubuntu/grafana-11.1.3.linux-amd64.tar.gz

    - name: Extract Grafana tarball
      unarchive:
        src: /home/ubuntu/grafana-11.1.3.linux-amd64.tar.gz
        dest: /home/ubuntu/
        remote_src: yes
        extra_opts:
          - --strip-components=1

    - name: List contents of /home/ubuntu/grafana-11.1.3/bin for debugging
      command: ls -l /home/ubuntu/grafana-11.1.3/bin/
      register: grafana_bin_contents
      failed_when: false

    - name: Print contents of grafana bin directory
      debug:
        msg: "{{ grafana_bin_contents.stdout }}"

    - name: Check if grafana-server exists
      stat:
        path: /home/ubuntu/grafana-11.1.3/bin/grafana-server
      register: grafana_server_stat

    - name: Print grafana-server file status
      debug:
        msg: "grafana-server file exists: {{ grafana_server_stat.stat.exists }}"

    - name: Move Grafana server binary to /usr/local/bin
      command: cp /home/ubuntu/grafana-11.1.3/bin/grafana-server /usr/local/bin/
      args:
        creates: /usr/local/bin/grafana-server

    - name: Ensure /etc/systemd/system directory exists
      file:
        path: /etc/systemd/system
        state: directory

    - name: Copy Grafana systemd service file
      copy:
        src: templates/grafana.service
        dest: /etc/systemd/system/grafana.service
        mode: '0644'
      notify:
       - Reload systemd daemon
       - Start and enable Grafana service
       
    - name: Start Grafana in background using nohup
      shell: |
        nohup /home/ubuntu/grafana-9.6.3/linux-amd64/grafana-server --config=/etc/grafana/grafana.ini > /var/log/grafana.log 2>&1 &
      args:
        chdir: /home/ubuntu/
      # Ensure the Grafana process runs in the background
      changed_when: false


  handlers:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana
        state: started
        enabled: yes
