---
- name: Run node_exporter
  hosts: webservers
  become: true
  tasks:
    - name: Download Grafana script
      debug:
        msg: Copying Grafana script
      copy:
        src: /home/ubuntu/git/grafana.sh
        dest: /home/ubuntu/
        mode: 0755

    - name: Run the Grafana script
      debug:
        msg: Running Grafana script
      command: bash /home/ubuntu/grafana.sh
    # - name: Run Grafana
    #   command: nohup /home/ubuntu/grafana-v11.1.3/bin/grafana-server web
...