---
- name: Run node_exporter
  hosts: webservers
  become: true
  tasks:
    - name: Download Grafana script
      copy:
        src:  /root/Ansible-Monitoring/grafana.sh
        dest: /home/ubuntu/grafana.sh
        mode: '0755'
      
    - name: Run the Grafana script
      command: bash /home/ubuntu/grafana.sh

    - name: Ensure Grafana service is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes
...

