---
- name: Manage Grafana
  hosts: webservers
  become: true
  tasks:
    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory

    - name: Download Grafana script
      copy:
        src: /root/Ansible-Monitoring/grafana.sh
        dest: /home/ubuntu/grafana.sh
        mode: '0755'

    - name: Run the Grafana script
      command: bash /home/ubuntu/grafana.sh
      args:
        chdir: /home/ubuntu/
      # Ensure the script is idempotent
      changed_when: false

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Verify Grafana service status
      command: systemctl status grafana-server
      register: grafana_status
      failed_when: "'active (running)' not in grafana_status.stdout"
