---
- name: Manage Grafana
  hosts: webservers
  become: true
  tasks:
    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory

    - name: Download Grafana script
      copy:
        src: /root/Ansible-Monitoring/grafana.sh
        dest: /home/ubuntu/grafana.sh
        mode: '0755'

    - name: Run the Grafana script
      command: bash /home/ubuntu/grafana.sh
      args:
        chdir: /home/ubuntu/
      # Ensure the script is idempotent
      changed_when: false

    - name: Ensure /etc/systemd/system directory exists
      file:
        path: /etc/systemd/system
        state: directory

    - name: Copy Grafana systemd service file
      copy:
        src: /root/Ansible-Monitoring/grafana.service
        dest: /etc/systemd/system/grafana.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Start and enable Grafana service

  handlers:
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana
        state: started
        enabled: yes
