- name: Manage Node Exporter
  hosts: node
  become: true
  tasks:
    - name: Ensure /home/ubuntu directory exists
      file:
        path: /home/ubuntu
        state: directory

    - name: Download Node Exporter tarball
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /home/ubuntu/node_exporter-1.8.2.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Node Exporter tarball
      unarchive:
        src: /home/ubuntu/node_exporter-1.8.2.linux-amd64.tar.gz
        dest: /home/ubuntu
        remote_src: yes
      notify:
        - Ensure Node Exporter binary permissions
        - Create Node Exporter systemd service file

    - name: Ensure Node Exporter binary permissions
      file:
        path: /home/ubuntu/node_exporter-1.8.2.linux-amd64/node_exporter
        mode: '0755'
        state: file

    - name: Create Node Exporter systemd service file
      template:
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Restart node_exporter

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes

  handlers:
    - name: Ensure Node Exporter binary permissions
      file:
        path: /home/ubuntu/node_exporter-1.8.2.linux-amd64/node_exporter
        mode: '0755'
        state: file

    - name: Create Node Exporter systemd service file
      template:
        src: templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart node_exporter
      systemd:
        name: node_exporter
        state: restarted
