---
- name: Install Prometheus
  hosts: webservers
  become: true
  tasks:
    - name: Download Prometheus script
      copy:
        src:  /home/ubuntu/git/prometheus.sh  
        dest: /home/ubuntu/
        mode: 0755  
    - name: Run the Prometheus script
      command: bash /home/ubuntu/prometheus.sh
      
...
