- name: Manage Prometheus
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure /etc/prometheus directory exists
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Download Prometheus script
      copy:
        src: /root/Ansible-Monitoring/prometheus.sh  
        dest: /home/ubuntu/prometheus.sh
        mode: '0755'

    - name: Run the Prometheus script
      command: bash /home/ubuntu/prometheus.sh
      args:
        chdir: /home/ubuntu/
      # Ensure the script is idempotent
      changed_when: false

    - name: Ensure prometheus.yml configuration is correct
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify:
        - Restart prometheus

    - name: Ensure Prometheus systemd service file exists
      template:
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Restart prometheus

    - name: Enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes
      # Ensure service is enabled regardless of its current state
      changed_when: false

    - name: Start Prometheus service
      systemd:
        name: prometheus
        state: started
      # Ensure service is started regardless of its current state
      changed_when: false

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      # Run this task unconditionally; no need for conditional checks
      # Remove the conditional check that was causing issues

  handlers:
    - name: Restart prometheus
      systemd:
        name: prometheus
        state: restarted

