- name: Manage Prometheus
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure /etc/prometheus directory exists
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Download Prometheus script
      copy:
        src: /root/Ansible-Monitoring/prometheus.sh  
        dest: /home/ubuntu/prometheus.sh
        mode: '0755'

    - name: Run the Prometheus script
      command: bash /home/ubuntu/prometheus.sh

    - name: Ensure prometheus.yml configuration is correct
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify:
        - Restart prometheus

    - name: Ensure Prometheus systemd service file exists
      template:
        src: /root/Ansible-Monitoring/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Restart prometheus

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

  handlers:
    - name: Restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
