- name: Manage Prometheus
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure /etc/prometheus directory exists
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Download Prometheus script
      copy:
        src: /root/Ansible-Monitoring/prometheus.sh  
        dest: /home/ubuntu/prometheus.sh
        mode: '0755'

    - name: Run the Prometheus script
      command: bash /home/ubuntu/prometheus.sh
      args:
        chdir: /home/ubuntu/
      changed_when: false

    - name: Ensure prometheus.yml configuration is correct
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify:
        - Restart prometheus

    - name: Ensure Prometheus systemd service file exists
      template:
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'
      notify:
        - Reload systemd daemon
        - Restart prometheus

    - name: Start Prometheus in background using nohup
      shell: |
        nohup /home/ubuntu/prometheus-2.53.1.linux-amd64/prometheus --config.file=/etc/prometheus/prometheus.yml > /var/log/prometheus.log 2>&1 &
      args:
        chdir: /home/ubuntu/
      # Ensure the Prometheus process runs in the background
      changed_when: false

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

  handlers:
    - name: Restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
